finders: # The list of finders to be used
  - namespace: "minecraft:compass" # The namespace of the finder
    range: 30 # The range in blocks to search for containers
    # The list of container namespace to search for (e.g., chests, furnaces, etc.).
    containers:
      - "minecraft:chest"
      - "minecraft:furnace"

messages:
  # Sent to the player when the finder is used
  # {containers} will be replaced with the number of containers found
  # {range} will be replaced with the finder's range
  result: "&7UnclaimFinder &8| &7&c{containers} &7conteneur(s) trouvé(s) dans un rayon de &c{range} &7bloc(s)"
