name: UnclaimFinder
version: '1.0-SNAPSHOT'
description: UnclaimFinder is a plugin that allows players to find containers in a specified range
authors: [ Choukas ]
main: fr.vlrjuan.unclaimfinder.UnclaimFinderPlugin
api-version: '1.20'
depend: [ ItemsAdder ]
